[workspace.package]
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
keywords = ["alpm", "arch", "linux", "packaging"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
edition = "2021"
authors = [
  "David Runge <dvzrv@archlinux.org>",
  "Orhun Parmaksız <orhun@archlinux.org>",
  "Arne Beer <contact@arne.beer>"
]

[workspace]
resolver = "2"
members = ["alpm-buildinfo", "alpm-parsers", "alpm-types"]

[workspace.dependencies]
clap = { version = "4.5.19", features = ["derive", "env", "string"] }
rstest = "0.23.0"
strum = "0.26.3"
thiserror = "1.0.40"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
