[workspace.package]
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
keywords = ["alpm", "arch", "linux", "packaging"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
edition = "2021"
authors = [
  "David Runge <dvzrv@archlinux.org>",
  "Orhun Parmaksız <orhun@archlinux.org>",
  "Arne Beer <contact@arne.beer>",
]

[workspace]
resolver = "2"
members = ["alpm-buildinfo", "alpm-parsers", "alpm-types", "dev-scripts"]

[workspace.dependencies]
assert_cmd = "2.0.11"
clap = { version = "4.5.19", features = ["derive", "env", "string"] }
insta = "1.40.0"
rstest = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
testresult = "0.4.1"
thiserror = "2.0.0"
winnow = "0.6"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
