# configuration for <https://github.com/crate-ci/committed>
## see the reference: <https://github.com/crate-ci/committed/blob/master/docs/reference.md>

# commit message rules
style = "conventional"
subject_capitalized = false
imperative_subject = true
subject_not_punctuated = true
line_length = 72
subject_length = 0 # disable the check

# commit types
no_fixup = true
no_wip = true
merge_commit = false
