# SPDX-FileCopyrightText: 2023 David Runge <dvzrv@archlinux.org>
# SPDX-License-Identifier: CC0-1.0

[advisories]
version = 2
yanked = "deny"
ignore = []

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "LGPL-3.0",
    "MIT",
    "Unicode-DFS-2016",
]

[bans]
multiple-versions = "allow"
