[advisories]
ignore = [
    # Possible valid string to invalid string bug.
    # This dependency is only included when winnow is compiled with the debug flag.
    "RUSTSEC-2024-0404",
    # The ring crate is unmaintained.
    # We (currently) only use it via the "reqwest" crate in the "dev-scripts" crate.
    # https://github.com/seanmonstar/reqwest/issues/2566
    "RUSTSEC-2025-0007",
]
version = 2
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
]
version = 2

[[licenses.clarify]]
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"
version = "*"

[bans]
multiple-versions = "allow"
