[package]
authors = ["David Runge <dvzrv@archlinux.org>"]
description = "Types for Arch Linux Package Management"
edition = "2021"
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
keywords = ["alpm", "arch", "linux", "packaging"]
license = "Apache-2.0 OR MIT"
name = "alpm-types"
readme = "README.md"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
rust-version = "1.67.1"
version = "0.4.0"

[dependencies]
blake2 = "0.10.6"
digest = "0.10.7"
email_address = "0.2.4"
md-5 = "0.10.5"
once_cell = "1.18.0"
regex = "1.10.2"
semver = "1.0.17"
sha1 = "0.10.5"
sha2 = "0.10.7"
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.43"
time = "0.3.22"
url = "2.4.0"

[dev-dependencies]
proptest = "1.4.0"
rstest = "0.18.1"
