[package]
authors = ["David Runge <dvzrv@archlinux.org>"]
description = "Library and commandline toolkit for the specification, writing and parsing of ALPM BUILDINFO files"
edition = "2021"
exclude = ["/.ci/", ".gitlab-ci.yml"]
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
keywords = ["alpm", "arch", "linux", "packaging", "buildinfo"]
license = "Apache-2.0 OR MIT"
name = "alpm-buildinfo"
readme = "README.md"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
rust-version = "1.70.0"
version = "0.1.0"

[build-dependencies]
mandown = "0.1.3"

[dependencies]
alpm-types = { path = "../alpm-types" }
clap = { version = "4.5.19", features = ["derive", "string"] }
clap_complete = "4.5.32"
clap_mangen = "0.2.12"
thiserror = "1.0.40"
strum = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0.11"
rstest = { workspace = true }
testdir = "0.9.1"
testresult = "0.4.1"
