[package]
name = "alpm-buildinfo"
description = "Library and commandline toolkit for the specification, writing and parsing of ALPM BUILDINFO files"
version = "0.1.0"
rust-version = "1.70.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
alpm-parsers = { path = "../alpm-parsers" }
alpm-types = { path = "../alpm-types" }
clap.workspace = true
serde.workspace = true
serde_with = "3.11.0"
thiserror.workspace = true

[dev-dependencies]
assert_cmd = "2.0.11"
insta = "1.40.0"
rstest.workspace = true
testdir = "0.9.1"
testresult.workspace = true
