# SPDX-FileCopyrightText: 2023 David Runge <dvzrv@archlinux.org>
# SPDX-License-Identifier: CC0-1.0

[package]
authors = ["David Runge <dvzrv@archlinux.org>"]
description = "Library and commandline toolkit for the specification, writing and parsing of ALPM BUILDINFO files"
edition = "2021"
exclude = ["/.ci/", ".gitlab-ci.yml"]
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm-buildinfo"
keywords = ["alpm", "arch", "linux", "packaging", "buildinfo"]
license = "LGPL-3.0-or-later AND GPL-3.0-or-later"
name = "alpm-buildinfo"
readme = "README.md"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm-buildinfo"
rust-version = "1.60.0"
version = "0.0.0"

# Tweak release profile settings for faster code.
# - enable link time optimization
# - reduce the code generation units
# See <https://doc.rust-lang.org/cargo/reference/profiles.html>
[profile.release]
lto = true
codegen-units = 1

[build-dependencies]
mandown = "0.1.3"

[dependencies]
alpm-types = "0.3.0"
clap = { version = "4.3.3", features = ["derive", "string"] }
clap_complete = "4.3.1"
clap_mangen = "0.2.12"
strum = "0.24.1"
thiserror = "1.0.40"

[dev-dependencies]
assert_cmd = "2.0.11"
rstest = "0.17.0"
testdir = "0.8.0"
testresult = "0.3.0"
