[package]
authors = ["David Runge <dvzrv@archlinux.org>"]
description = "Library and commandline toolkit for the specification, writing and parsing of ALPM BUILDINFO files"
edition = "2021"
homepage = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
keywords = ["alpm", "arch", "linux", "packaging", "buildinfo"]
license = "Apache-2.0 OR MIT"
name = "alpm-buildinfo"
readme = "README.md"
repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
rust-version = "1.70.0"
version = "0.1.0"

[dependencies]
alpm-types = { path = "../alpm-types" }
clap.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_cmd = "2.0.11"
insta = "1.40.0"
rstest.workspace = true
testdir = "0.9.1"
testresult = "0.4.1"
