[package]
name = "alpm-mtree"
description = "Library and commandline toolkit for the specification, writing and parsing of ALPM .MTREE files"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "alpm-mtree"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["dep:clap"]
default = ["cli"]
winnow-debug = ["winnow/debug"]

[dependencies]
alpm-types.workspace = true
clap = { workspace = true, optional = true }
flate2 = "1"
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
winnow.workspace = true

[dev-dependencies]
insta.workspace = true
rstest.workspace = true
testresult.workspace = true
