[package]
name = "dev-scripts"
version = "0.0.0"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true

# This is a development crate. Never publish it.
publish = false

[dependencies]
anyhow = "1"
clap.workspace = true
dirs = "5"
log = "0.4"
simplelog = { version = "0.12", default-features = false }
strum.workspace = true
