[package]
name = "dev-scripts"
version = "0.0.0"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true

# This is a development crate. Never publish it.
publish = false

[dependencies]
alpm-buildinfo = { path = "../alpm-buildinfo" }
anyhow = "1"
clap.workspace = true
colored = "2"
dirs = "5"
indicatif = "0.17"
log = "0.4"
rayon = "1"
reqwest = { version = "0.12", default-features = false, features = [
  "charset",
  "blocking",
  "http2",
  "json",
  "rustls-tls",
] }
simplelog = { version = "0.12", default-features = false }
strum.workspace = true

[dev-dependencies]
rstest.workspace = true
tempfile = "3"
